version: "3.8"
services:
  node_18:
    container_name: "SERVER_B"
    build: 
      context: .
      dockerfile: ./dockerFile
    environment:
      - NODE_OPTIONS=--max_old_space_size=8000
    ports:
      - "${NODE_PORT}:${NODE_PORT_MAPPED}"
    volumes:
      - .:/usr/src/server_B
    networks:
      - claro_server_b
      - claro_shared_network
  mysql_server_b:
    container_name: DB_B
    image: mysql:8.1.0
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT_MAPPED}"
    environment:
      MSQL_OPTS: --skip-host-cache
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - DB_B_VOLUMES:/var/lib/mysql
    networks:
      - claro_server_b
volumes:
  DB_B_VOLUMES:
networks:
  claro_server_b:
  claro_shared_network  :
    external : true